### ISSUE TITLE
NextJS support

### ISSUE THREAD

**Issue by wildsonc** [borisbelmar/arrow-navigation#44]
Is it possible to use this library with NextJS?

I added `initArrowNavigation()` to my root layout:

```tsx
# Fix: ReferenceError: window is not defined
if (typeof window !== "undefined") {
  initArrowNavigation();
}
```

With this in development mode the only error I get is:

`Internal error: Error: ArrowNavigation is not initialized`

However, even with this error it works, I believe this error is only due to the fact that I use `typeof window !== "undefined"` in my layout.

Is there any other way I should do this? Because even though it is working, I can't build it because of this error.

**Comment by borisbelmar** [comment]
@wildsonc Hey! Apologies for the delayed response. You can initialize it within a client component, specifically inside a useEffect. At the moment, it hasn’t been tested with Next.js. That said, I’m not sure how practical a Next.js app would be for TVs, considering that TV environments typically run entirely on the client side.
